name: Deploy Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io
      - uses: bhowell2/github-substring-action@1.0.2
        id: sha
        with:
          value: ${{ github.event.pull_request.head.sha }}
          length_from_start: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.2
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: quay.io/subscan-explorer/subscan-essentials-ui:sha-${{ steps.short-sha.outputs.sha }}-${{ github.run_number }}
