name: Deploy Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.2
          cache: 'npm'
      - name: Install dependencies && build
        run: npm install && npm run build
      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: quay.io/subscan-explorer/subscan-essentials-ui:sha-${{ steps.short-sha.outputs.sha }}-${{ github.run_number }}
